### ISSUE TITLE
Custom message support for alert & snackbar

### ISSUE THREAD

**Issue by c1pr1an** [Oauth-Celestial/Connectivity_Watcher#1]
Great wrapper, works fantastic so far! 
I have a feature request: It would be fantastic to have access to the message that's displayed to the user as snackbar or alert, instead of creating custom widget if I want to display a different text.
Thanks

**Comment by Oauth-Celestial** [comment]
Thanks for the suggestion  @c1pr1an  we will implement this in the upcoming release
