### ISSUE TITLE
Need to perform some API calls when Internet Back, 

### ISSUE THREAD

**Issue by avnp16** [Oauth-Celestial/Connectivity_Watcher#2]
Need to perform some API calls when Internet Back , how can I do without any custom click to check internet ?

**Comment by Oauth-Celestial** [comment]
@avnp16  Currently you can check the internet status only with the package . Can you please elaborate  so i can help

**Comment by avnp16** [comment]
When internet down, then bottom snack bar comes with no
internet connection, when internet update then , it's disappear, I want to
perform some actions when it's disappear, means on internet comes/on of
every event, need to perform my personal APIs/ codes

**Comment by Oauth-Celestial** [comment]
Thanks for the explanation @avnp16 . Currently the package on supports displaying the status of the internet. But the use case you have is valid so will include the  implementation in the upcoming release

**Comment by Oauth-Celestial** [comment]
@avnp16  The requested feature has been added thanks for the issue request
